---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appcolor
  name: appcolor-dev-svc
spec:
  ports:
  - name: appcolor-dev-svc-port
    port: 5000
    targetPort: 5000
  selector:
    app: appcolor
