---
apiVersion: v1
kind: Namespace
metadata:
  name: appcolor
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: appcolor
  name: appcolor-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/marcos2soares/ARGOCD-OPENSHIFT.git
    contextDir: source_appcolor
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: appcolor:v1.0
  triggers:
    - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: appcolor
  name: appcolor
spec:
  lookupPolicy:
    local: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-binding-dev
  namespace: appcolor
subjects:
- kind: ServiceAccount
  name: default
  namespace: appcolor-dev
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-binding-prd
  namespace: appcolor
subjects:
- kind: ServiceAccount
  name: default
  namespace: appcolor-prd
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
