apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcolor-build
  namespace: openshift-gitops
spec:
  destination:
    namespace: appcolor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: build_appcolor/base
    repoURL: https://github.com/marcos2soares/ARGOCD-OPENSHIFT.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
