---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller-binding-prd
  namespace: appcolor
subjects:
- kind: ServiceAccount
  name: default
  namespace: appcolor-prd
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
