apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appcolor-prd-{VERSAO}
  namespace: openshift-gitops
spec:
  destination:
    namespace: appcolor-prd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prd_appcolor/{VERSAO}
    repoURL: https://github.com/marcos2soares/ARGOCD-OPENSHIFT.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences: 
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
