apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: appcolor
  namespace: openshift
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/appcolor:{VERSAO}
    importPolicy: {}
    referencePolicy:
      type: Source
