---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appcolor
    versao: v1.0
  name: appcolor-dev-svc-v1-0
spec:
  ports:
  - name: appcolor-dev-svc-port-v1-0
    port: 5000
    targetPort: 5000
  selector:
    app: appcolor
    versao: v1.0
