---
apiVersion: v1
kind: Namespace
metadata:
  name: appcolor-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appcolor
    app.kubernetes.io/part-of: appcolor-dev-v1.0
  name: appcolor-dev-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appcolor
  template:
    metadata:
      labels:
        app: appcolor
    spec:
      containers:
        - image: default-route-openshift-image-registry.apps.ocplab.vtal.intra/appcolor/appcolor:v1.0
          name: appcolor
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: 'random'
    haproxy.router.openshift.io/disable_cookies: 'true'
  labels:
    app: appcolor
  name: appcolor-dev-route-2
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: appcolor-dev-svc
    weight: 100
  port:
    targetPort: appcolor-dev-svc-port
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: appcolor
  name: appcolor-dev-route
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: appcolor-dev-svc
    weight: 100
  port:
    targetPort: appcolor-dev-svc-port
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appcolor
  name: appcolor-dev-svc
spec:
  ports:
  - name: appcolor-dev-svc-port
    port: 5000
    targetPort: 5000
  selector:
    app: appcolor
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appvt12117-dev-hpa
  labels:
    app: appcolor
spec:
  maxReplicas: 15
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appcolor-dev-deploy
