apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: appcolor
  namespace: appcolor-prd
spec:
  lookupPolicy:
    local: true
  tags:
  - name: v1.0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/appcolor/appcolor:v1.0
    importPolicy: {}
    referencePolicy:
      type: Source
